feat: Updated script/bootstrap

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -4,7 +4,15 @@ set -e
 STATUS=0
 
 { ruby --version
-  bundle install
+  if ! ruby -v | grep -q "ruby 2.6.10"; then
+    echo "Required Ruby version 2.6.10 or higher is not installed" >&2
+    STATUS=1
+  fi
+  bundle _1.17.2_ install
+  if ! bundle -v | grep -q _1.17.2_; then
+    echo "Required Bundler version 1.17.2 is not installed" >&2
+    STATUS=1
+  fi
   bundle binstub cucumber --path bin
 } || {
   echo "You need Ruby 1.9 or higher and Bundler to run hub tests" >&2
@@ -15,4 +23,7 @@ if [ $STATUS -eq 0 ]; then
   echo "Everything OK."
 fi
 
+elif [ $STATUS -ne 0 ]; then
+  	echo "Ruby and Bundler requirements not met" >&2
+fi
 exit $STATUS
